name: Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build.yml
        with:
          artifact-name: build

  dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: ./.github/workflows/deploy.yml
        with:
          env: dev
          artifact-name: build

  stage:
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - uses: ./.github/workflows/deploy.yml
        with:
          env: stage
          artifact-name: build

  prod:
    runs-on: ubuntu-latest
    needs: stage
    steps:
      - uses: ./.github/workflows/deploy.yml
        with:
          env: prod
          artifact-name: build
