name: Pipeline

on:
  push:
    tags:
      - v*
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: build

  dev:
    needs: build
    uses: ./.github/workflows/deploy.yml
    if: github.ref == 'refs/heads/main'
    with:
      env: dev
      artifact-name: build

  stage:
    needs: dev
    uses: ./.github/workflows/deploy.yml
    if: github.ref == 'refs/heads/main'
    with:
      env: stage
      artifact-name: build

  prod:
    needs: stage
    uses: ./.github/workflows/deploy.yml
    if: startsWith(github.ref, 'refs/tags/v')
    with:
      env: prod
      artifact-name: build
