name: Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: build

  dev:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
      artifact-name: build

  stage:
    needs: dev
    uses: ./.github/workflows/deploy.yml
    with:
      env: stage
      artifact-name: build

  prod:
    needs: stage
    uses: ./.github/workflows/deploy.yml
    with:
      env: prod
      artifact-name: build
